#!/usr/bin/env php
<?php
$user = get_current_user();
$config_path =  "./pybotrc";
if (!file_exists($config_path)) {
	die("FATAL: Could not find configuration in $config_path\n");
}
if (!is_readable($config_path)) {
    die("FATAL: Configuration file $config_path cannot be read or I don't have permission\n"); 
}

$pi = pathinfo(__FILE__);
$_cwd = $pi['dirname'];

include $config_path;
include $_cwd . '/lib/irc.php';

$ircClass = array(
                'filename'  => 'irc.php',
                'origclass' => 'Irc',
                'classname' => 'Irc',
                'md5sum'    => md5_file($_cwd . '/lib/irc.php'),
                'directory' => $_cwd . '/lib'
            );

$config['_classes'] = array('Irc' => $ircClass);
$config['_methods'] = array();
$config['_cwd'] = $_cwd;

unset($pi, $config_path, $ircClass);
// include $_cwd . '/lib/transmissionrpc.php';

// We keep this here because it's not user configurable
// and to avoid having to change config files every iteration

$config['version'] = '4.1.'.file_get_contents('VERSION');

require_once $_cwd . '/oauth/tmhOAuth.php';

$pybs = new Irc($config);
exit;
