#!/usr/bin/env php
<?php
$config_path =  "./pybotrc";
if (!file_exists($config_path)) {
	die("FATAL: Could not find configuration in $config_path\n");
}
if (!is_readable($config_path)) {
    die("FATAL: Configuration file $config_path cannot be read or I don't have permission\n"); 
}

$pi = pathinfo(__FILE__);
$_cwd = $pi['dirname'];

include $config_path;
include $_cwd . '/lib/simple_html_dom.php';
include $_cwd . '/lib/irc.php';

$ircClass = array(
                'filename'  => 'irc.php',
                'origclass' => 'Irc',
                'classname' => 'Irc',
                'md5sum'    => md5_file($_cwd . '/lib/irc.php'),
                'directory' => $_cwd . '/lib'
            );

$config['_classes'] = array('Irc' => $ircClass);
$config['_methods'] = array();
$config['_cwd'] = $_cwd;
$config['_starttime'] = date('U');
$config['_configChecksum'] = md5_file($config_path);
$config['_configPath'] = $config_path;
$config['_dateFormat'] = 'd-m-Y H:i';


unset($pi, $config_path, $ircClass);
// include $_cwd . '/lib/transmissionrpc.php';

// We keep this here because it's not user configurable
// and to avoid having to change config files every iteration

$v = file_get_contents('VERSION');
$config['versionString'] = $v;
$config['_versionChecksum'] = md5($v);

require_once $_cwd . '/tmhoauth/tmhOAuth.php';

$pybs = new Irc($config);
exit;
