#!/usr/bin/env php
<?php
$user = get_current_user();
$config_path =  "./pybotrc";
if (!file_exists($config_path)) {
	die("FATAL: Could not find configuration in $config_path\n");
}
if (!is_readable($config_path)) {
    die("FATAL: Configuration file $config_path cannot be read or I don't have permission\n"); 
}

$pi = pathinfo(__FILE__);
$_cwd = $pi['dirname'];

include $config_path;
include $_cwd . '/lib/irc.php';
include $_cwd . '/lib/log.php';
include $_cwd . '/lib/curl.php';
include $_cwd . '/lib/simple_html_dom.php';

$ircClass = array(
                'filename'  => 'irc.php',
                'classname' => 'Irc',
                'md5sum'    => md5_file($_cwd . '/lib/irc.php')
            );

$config['_classes'] = array('Irc' => $ircClass);
$config['_methods'] = array();
$config['_cwd'] = $_cwd;

unset($pi, $config_path, $ircClass);
// include $_cwd . '/lib/transmissionrpc.php';
# Required for twitter
require $_cwd . '/oauth/tmhOAuth.php';
#require $_cwd . '/oauth/tmhUtilities.php';

// We keep this here because it's not user configurable
// and to avoid having to change config files every iteration

$config['version'] = '4.1.'.file_get_contents('VERSION');

include $_cwd.'/lib/actions.php';
include $_cwd.'/lib/bleacher.php';
include $_cwd.'/lib/strings.php';

$pybs = new Irc($config);
unset($pybs);
$namespace = 'Pybot0';
include $_cwd.'/lib/tttttt.php';
$pybs = new Irc();
exit;
